### ISSUE TITLE
on the fly meta-data preservation through use of gzip

### ISSUE THREAD

**Issue by bdeetz** [SpectraLogic/ds3_net_sdk#110]
I'm looking to be able to preserve the meta-data (extended attributes, permission, etc) via gzipping each file uploaded when I execute something like

`Thread transferT = new Thread(() => job.Transfer(FileHelpers.BuildFilePutter(folderSourceDialog.SelectedPath)));`

I was hoping to perform the gzip on the fly within the ds3 library.

After looking at the code, it seems like blobbing may make this a more difficult task than the the idea appears at the surface.

Do you have any ideas on how I could accomplish gzipping a file on the fly as it is being uploaded or at the least right before it is uploaded. I'd prefer not to walk the filesystem and gzipping everything before starting the upload process?

**Comment by bdeetz** [comment]
On the other hand, I could just walk the filesystem and store all metadata in a sqlite or similar database before calling the Job.Transfer.

Again, what would you recommend?

**Comment by rpmoore** [comment]
We are adding metadata support to our helper functions so that you can upload metadata while transferring files.  This functionality will be exposed within the next week or so, and gives you the ability to register a callback function which will when called provides metadata as key value pairs of strings.

I'll leave this open until the feature is released.

**Comment by rpmoore** [comment]
We just released [v3.0.1](https://github.com/SpectraLogic/ds3_net_sdk/releases/tag/v3.0.1) which adds metadata support to the helper functions.  We've also added an example ([here](https://github.com/SpectraLogic/ds3_net_sdk/blob/3_0_autogen/Ds3Examples/WithMetadataExample.cs)) which shows how to use it.  If you have any questions please let us know.
