### ISSUE TITLE
Fully Qualified Filename Length Limitation

### ISSUE THREAD

**Issue by bdeetz** [SpectraLogic/ds3_net_sdk#160]
Due to .Net's limit of 248 character paths, despite NTFS supporting 32000, I am getting exceptions when I call Ds3.Helpers.Ds3ClientHelpers.StartWriteJob.

In my own code, I have addressed this issue by using Delimon.Win32.IO; instead of System.IO.

Is it possible to resolve this here instead of me maintaining a patch set for ds3_net_sdk?

**Comment by shabtaisharon** [comment]
Are you getting the exception when using the StartWriteJob function or when using job.Transfer?
Can you paste here a snippet of your failing code?

**Comment by bdeetz** [comment]
It's actually in the FileHelpers class that I was getting exceptions.

Ds3/Helpers/FileHelpers.cs

It takes a while to get the exception, so this screenshot is the best I can provide at the moment.

![screenshot_2016-08-05-11-19-54](https://cloud.githubusercontent.com/assets/4131714/17450723/80e8b922-5b27-11e6-9113-f5ea69deb69c.png)

I'm currently testing the attached patched version of FileHelpers.cs. Sorry for being lazy and not forking, branching, and pull-requesting.
[FileHelpers.cs.txt](https://github.com/SpectraLogic/ds3_net_sdk/files/404638/FileHelpers.cs.txt)

**Comment by shabtaisharon** [comment]
Our file helpers has the .Net limitation concerning the number of chars, and it looks like your new file helpers could be your solution in this case.

Let me know how it goes

**Comment by bdeetz** [comment]
So, yes moving to the other library worked just fine for me. I've just broken that code out into a new helper class to avoid having to maintain patches. Thanks for confirming the .Net limitation within this library.

**Comment by shabtaisharon** [comment]
Sure :+1:
